TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/spi_slave.v
TOPLEVEL      = spi_slave
MODULE        = test_spi

# choose your simulator, e.g. icarus
SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
